owner: openvoiceos
repo: status

sites:
  - name: Text-to-Speech - Mimic3 - Ziggyai
    url: https://mimic3.ziggyai.online/status
    maxResponseTime: 60000
    assignees:
      - builderjer
  - name: Text-to-Speech - Piper - Ziggyai
    url: https://pipertts.ziggyai.online/status
    maxResponseTime: 60000    
    assignees:
      - builderjer
  - name: Text-to-Speech - Matxa - Ziggyai
    url: https://matxa.ziggyai.online/status
    maxResponseTime: 60000    
    assignees:
      - builderjer
  - name: Text-to-Speech - Mimic - Smart'Gic
    url: https://tts.smartgic.io/mimic/status
    assignees:
      - goldyfruit
  - name: Text-to-Speech - Piper - Smart'Gic
    url: https://tts.smartgic.io/piper/status
    assignees:
      - goldyfruit
  - name: Text-to-Speech - SAM - Smart'Gic
    url: https://tts.smartgic.io/sam/status
    assignees:
      - goldyfruit
  - name: Text-to-Speech - Matxa - Smart'Gic
    url: https://tts.smartgic.io/matxa/status
    assignees:
      - goldyfruit
  - name: Text-to-Speech - Coqui - Neon AI
    url: https://coqui.neonaibeta.com/status
    assignees:
      - NeonDaniel
  - name: Text-to-Speech - Coqui 2 - Neon AI
    url: https://coqui.neonaialpha.com/status
    assignees:
      - NeonDaniel
  - name: Text-to-Speech - Coqui 3 - Neon AI
    url: https://coqui.neonaiservices.com/status
    assignees:
      - NeonDaniel
  - name: Speech-to-Text - Faster Whisper - Ziggyai
    url: https://fasterwhisper.ziggyai.online/status
    maxResponseTime: 60000    
    assignees:
      - builderjer
  - name: Speech-to-Text - Citrinet - Ziggyai
    url: https://citrinetstt.ziggyai.online/status
    maxResponseTime: 60000    
    assignees:
      - builderjer
  - name: Speech-to-Text - AINA - Ziggyai
    url: https://ainastt.ziggyai.online/status
    maxResponseTime: 60000    
    assignees:
      - builderjer
  - name: Speech-to-Text - Faster Whisper - Smart'Gic
    url: https://stt.smartgic.io/fasterwhisper/status
    assignees:
      - goldyfruit
  - name: Speech-to-Text - Faster Whisper - Neon AI
    url: https://whisper.neonaiservices.com/status
    assignees:
      - NeonDaniel
  - name: Speech-to-Text - NeMo - Smart'Gic
    url: https://stt.smartgic.io/nemo/status
    assignees:
      - goldyfruit
  - name: Speech-to-Text - AINA - Smart'Gic
    url: https://stt.smartgic.io/aina/status
    assignees:
      - goldyfruit
  - name: Speech-to-Text - Citrinet - Smart'Gic
    url: https://stt.smartgic.io/citrinet/status
    assignees:
      - goldyfruit
  - name: Speech-to-Text - NeMo - Neon AI
    url: https://nemo.neonaialpha.com/status
    assignees:
      - NeonDaniel
  - name: Translator - NLLB - Smart'Gic
    url: https://translator.smartgic.io/nllb/status
    assignees:
      - goldyfruit
  - name: Translator - NLLB - Open Voice OS
    url: https://nllb.openvoiceos.org/status
    assignees:
      - j1nx
      - JarbasAl
  - name: Translator - NLLB - Ziggyai
    url: https://ovosnllb.ziggyai.online/status
    maxResponseTime: 60000
    assignees:
      - builderjer

status-website:
  theme: dark
  baseUrl: /status
  logoUrl: https://openvoiceos.org/wp-content/uploads/2021/04/ovos-egg.png
  name: Status Page
  introTitle: "Open Voice OS components status"
  introMessage: "Community servers"
  navbar:
    - title: Status
      href: /status
    - title: Open Voice OS
      href: https://openvoiceos.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
