owner: smartgic
repo: status

sites:
  - name: Text-to-Speech Blue Systems
    url: http://mycroft.blue-systems.com:59125/api/healthcheck
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
  - name: Text-to-Speech Ziggyai
    url: https://mimic3.ziggyai.online/api/healthcheck
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
  - name: Text-to-Speech Smart'Gic
    url: https://tts.smartgic.io/mimic3/api/healthcheck
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
  - name: Speech-to-Text Open Voice OS
    url: https://stt.openvoice.os/stt

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Open Voice OS components status"
  introMessage: "Text-to-Speech and Speech-to-Text community servers"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
