owner: openvoiceos
repo: status

sites:
  - name: Text-to-Speech - Mimic3 - Blue Systems
    url: http://mycroft.blue-systems.com:59125/api/healthcheck
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
  - name: Text-to-Speech - Mimic3 - Ziggyai
    url: https://mimic3.ziggyai.online/status
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
    assignees:
      - builderjer
  - name: Text-to-Speech - Piper - Ziggyai
    url: https://pipertts.ziggyai.online/status
    icon: https://github.com/rhasspy/piper/raw/master/etc/logo.png
    assignees:
      - builderjer
  - name: Text-to-Speech - Mimic3 - Smart'Gic
    url: https://tts.smartgic.io/mimic3/status
    icon: https://mycroft.ai/wp-content/uploads/2022/06/Mimic_color_600px.png
    assignees:
      - goldyfruit
  - name: Speech-to-Text - Faster Whisper - Open Voice OS
    url: https://stt.openvoiceos.org/status
    icon: https://i.ibb.co/Hg85Z3s/text-to-speech.png
    assignees:
      - j1nx
      - JarbasAl
  - name: Speech-to-Text - Faster Whisper - Ziggyai
    url: https://fasterwhisper.ziggyai.online/status
    icon: https://i.ibb.co/Hg85Z3s/text-to-speech.png
    assignees:
      - builderjer

status-website:
  theme: dark
  baseUrl: /status
  logoUrl: https://openvoiceos.org/wp-content/uploads/2021/04/ovos-egg.png
  name: Status Page
  introTitle: "Open Voice OS components status"
  introMessage: "Text-to-Speech and Speech-to-Text community servers"
  navbar:
    - title: Status
      href: /status
    - title: Open Voice OS
      href: https://openvoiceos.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
